title: "OASIS 95" # runic vaporware # three hyper runes
author: "meatless"
description: "a blog" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# forked from https://chadbaldwin.net/2021/03/14/how-to-build-a-sql-blog.html

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
